### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by IbertechS** [robsontenorio/mary-ui.com#1]
Hi,

What security is compatible with this package?

Thanks

**Comment by robsontenorio** [comment]
@IbertechS  This package is a set of UI components. Authentication, authorization and everything else not related to UI is up to you.

**Comment by IbertechS** [comment]
I added mary components package to a clean installation with breeze, and livewire on the components won't work. I want to try to use this package and then add security.

**Comment by robsontenorio** [comment]
@IbertechS I have not tested this package with any starter kit.

It is supposed to be used on a fresh Laravel project, without Breeze or Jetstream.

Of course you can try to add them later.
