### ISSUE TITLE
Help with typos

### ISSUE THREAD

**Issue by robsontenorio** [robsontenorio/mary-ui.com#2]
I really appreciate your help with typos at content of `resources/views/`. See https://mary-ui.com

### How to contribute 

1. Could you spot any typos across docs?
1. Create an issue per page
1. Then create a MR to solve it

-----
1. I will tag your issue/MR with `hacktoberfest` / `hacktoberfest-accepted `
1. **Only typos, please.**
1. **I am not looking** for entire paragraph rewriting, because I like to keep it clean.

**Comment by flushthemoney** [comment]
I would like to solve this issue, kindly assign it to me.

**Comment by faizan1191** [comment]
@robsontenorio can you point out any typo I haven't found any at resources/view/
Would love to contribute

**Comment by robsontenorio** [comment]
@flushthemoney @faizan1191 

Well, the author (me) never spots typos. So , I am asking for helping. 

No typos in file name, but contents. 

The docs https://mary-ui.com/
The source code /resources/views

**Comment by flushthemoney** [comment]
@robsontenorio I've sent a PR, kindly merge it with the **hacktoberfest-accepted** label.

**Comment by robsontenorio** [comment]
Thank you all !
