### ISSUE TITLE
Row Numbers Instead of ID

### ISSUE THREAD

**Issue by djoks** [robsontenorio/mary-ui.com#25]
Hi, I am new to your framework and so far I'm enjoying it.  I would like to know how I can display the row numbers (current iteration) of a row in a paginated table. I can't use the ID because my IDs are Auto Increment so when certain rows are deleted it messes with the count.

**Comment by robsontenorio** [comment]
This is the repository of maryUI docs. Please, open an issue on right repository. The link is on top right on maryUI docs site.
